spring.application.name=gigsaathi

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/gigsaathi
spring.datasource.username=postgres
spring.datasource.password=Raghu*1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false
